---
node_exporter_version: "0.18.1"
node_exporter_tarball_checksum: "sha256:b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
node_exporter_platform_suffix: "linux-amd64"
node_exporter_signature: "node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform_suffix }}"
node_exporter_dist_dir: "{{ node_exporter_dir }}/{{ node_exporter_signature }}"
node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_signature }}.tar.gz"

node_exporter_user:  node_exporter
node_exporter_group: node_exporter

node_exporter_dir: "/opt/node-exporter"
node_exporter_storage_file: "https://storage.s3.us-east-2.amazonaws.com/node_exporter"
node_exporter_program: "{{ node_exporter_dir }}/node_exporter"
node_exporter_home: "/var/lib/node-exporter"
node_exporter_log_dir: "/var/log/node-exporter"

node_exporter_config_file: /etc/default/node-exporter
node_exporter_log_config: /etc/logrotate.d
node_exporter_pid_path: "/var/run"
node_exporter_log_path: "/var/log/node-exporter/node_exporter"
node_exporter_options: []

node_exporter_service_manage: true
node_exporter_service_enable: true
node_exporter_service_state: started
node_exporter_service_notify: true

node_exporter_cpu_shares: "128"
node_exporter_quota: "5%"
node_exporter_mem_limit: "128M"
node_exporter_dlock_io: "10"